Spring:
  output:
    ansi:
      enabled: always

  datasource:
    url: jdbc:mysql://localhost:3306/projectManager
    username: root
    password: password

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true

  mail:
    host: localhost
    port: 1025
    username: hello
    password: hello
#    properties:
#      mail:
#        smtp:
#          ssl:
#            trust: "*"
#          auth: true
#          starttls:
#            enable: true
#          connectiontimeout: 5000
#          timeout: 3000
#          writetimeout: 5000

#  file:
#    name: projectManagerLog.log
#  pattern:
#    console: %d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n
#logging:
#  level: debug

server:
  port: 3000
  error:
    include-message: always


app:
  jwtSecret: BAvl5GWxoeZRkbsqM244PpfUWU8UuCWQstBiO9fLRcJmgimSesfpVnkpMF62C5w
  jwtExpirationInMs: 86400000 # 24 hrs
